# Generated by Django 4.0.3 on 2022-03-20 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2022, 3, 20))),
            ],
        ),
    ]
